version: '3.3'
services:
  todo-front:
    build:
      context: ./todo-nuxt
      dockerfile: Dockerfile
    container_name: nuxt
    restart: unless-stopped
    ports:
      - 3000:3000
  todo-back:
    build:
      context: ./todo-api-prisma-express
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - 3300:3300